const backdrop=document.getElementById('modalBackdrop');const content=document.getElementById('modalContent');const close=document.getElementById('modalClose');
const templates={
 signup:`<span class="eyebrow">AUREN</span><h3>Build your system.</h3><p>Start with the basics. Your academic environment will grow around your goal.</p><form class="modal-form" onsubmit="demoSubmit(event,'Welcome to AUREN')"><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/><button class="dark-btn large" type="submit">Create account ↗</button></form><div class="demo-note">Demo mode — authentication will connect to Supabase in the next build phase.</div>`,
 login:`<span class="eyebrow">WELCOME BACK</span><h3>Good to see you.</h3><p>Log in to continue your academic system.</p><form class="modal-form" onsubmit="demoSubmit(event,'Logged in — demo mode')"><input required type="email" placeholder="Email address"/><input required type="password" placeholder="Password"/><button class="dark-btn large" type="submit">Log in ↗</button></form>`,
 tutor:`<span class="eyebrow">AI TUTOR</span><h3>Ask something.</h3><p>Try a question and see how AUREN can turn it into an explanation, a lesson or a challenge.</p><form class="modal-form" onsubmit="demoSubmit(event,'Tutor request queued')"><input required placeholder="e.g. explain why current decreases when resistance increases"/><button class="dark-btn large" type="submit">Ask AUREN ↗</button></form>`,
 practice:`<span class="eyebrow">INFINITE PRACTICE</span><h3>Never run out.</h3><p>Choose a subject and let the practice engine build a fresh set around you.</p><form class="modal-form" onsubmit="demoSubmit(event,'Practice set created')"><input required placeholder="Subject / topic"/><input placeholder="Exam (optional)"/><button class="dark-btn large" type="submit">Generate practice ↗</button></form>`,
 national:`<span class="eyebrow">AUREN NATIONAL</span><h3>Every Sunday.</h3><p>Register for the next All-India test and see how you compare.</p><form class="modal-form" onsubmit="demoSubmit(event,'You are registered for the demo test')"><input required placeholder="Email address"/><button class="dark-btn large" type="submit">Register ↗</button></form>`
};
function openModal(type){content.innerHTML=templates[type]||templates.signup;backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>content.querySelector('input')?.focus(),50)}
function closeModal(){backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function demoSubmit(e,message){e.preventDefault();content.innerHTML=`<span class="eyebrow">AUREN</span><h3>${message}</h3><p>This interface is ready for the real backend connection.</p><button class="dark-btn large" onclick="closeModal()">Continue ↗</button>`}
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
close.addEventListener('click',closeModal);backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const mobile=document.getElementById('mobileMenu');mobile.addEventListener('click',()=>{const nav=document.querySelector('.desktop-nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='78px';nav.style.left='0';nav.style.right='0';nav.style.padding='22px 20px';nav.style.background='rgba(243,240,233,.98)';nav.style.borderBottom='1px solid rgba(27,26,24,.14)';nav.style.flexDirection='column';nav.style.gap='18px'});
