const { createClient } = window.supabase;
const sb = createClient(window.AUREN_SUPABASE_URL, window.AUREN_SUPABASE_KEY, { auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true} });
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const overlay=$('#authOverlay'), authContent=$('#authContent'); let authBusy=false,otpCooldownUntil=0;
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=String(msg);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
const normalizeEmail=v=>String(v||'').trim().toLowerCase(); const validEmail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&e.length<=254; const validPassword=p=>typeof p==='string'&&p.length>=10&&p.length<=128; const validOtp=c=>/^\d{6}$/.test(String(c||'').trim());
function openAuth(mode='login'){overlay?.classList.remove('hidden');renderAuth(mode==='signup'?'signup':'login')} function closeAuth(){overlay?.classList.add('hidden');authBusy=false}
function el(tag,props={},text=''){const n=document.createElement(tag);Object.assign(n,props);if(text)n.textContent=text;return n}
function renderAuth(mode){const login=mode==='login';authContent.textContent='';const eyebrow=el('span',{className:'eyebrow'},'AUREN');const h2=el('h2',{},login?'welcome back.':'build your system.');const p=el('p',{},login?'continue where you left off.':'start with your email. your academic system grows around you.');const form=el('form',{className:'auth-form'});const email=el('input',{id:'authEmail',type:'email',autocomplete:'email',placeholder:'email address',required:true,maxLength:254});const password=el('input',{id:'authPassword',type:'password',autocomplete:login?'current-password':'new-password',placeholder:login?'password':'password · 10+ characters',required:true,maxLength:128});if(!login)password.minLength=10;const submit=el('button',{className:'pill-btn dark',type:'submit'},login?'log in ↗':'create account ↗');form.append(email,password,submit);const sw=el('div',{className:'auth-switch'},login?'new here? ':'already have an account? ');const swb=el('button',{type:'button'},login?'create account':'log in');sw.append(swb);const otp=el('div',{className:'auth-switch'}),otpBtn=el('button',{type:'button'},login?'use a one-time email code instead':'use email code instead');otp.append(otpBtn);authContent.append(eyebrow,h2,p,form,sw,otp);form.addEventListener('submit',login?passwordLogin:passwordSignup);swb.onclick=()=>renderAuth(login?'signup':'login');otpBtn.onclick=renderOtp}
function renderOtp(){authContent.textContent='';const eyebrow=el('span',{className:'eyebrow'},'EMAIL CODE'),h2=el('h2',{},'no password needed.'),p=el('p',{},"we'll send a one-time code to your email.");const form=el('form',{className:'auth-form'}),email=el('input',{id:'otpEmail',type:'email',autocomplete:'email',placeholder:'email address',required:true,maxLength:254}),submit=el('button',{className:'pill-btn dark',type:'submit'},'send code ↗');form.append(email,submit);const row=el('div',{className:'auth-switch'}),back=el('button',{type:'button'},'use password instead');row.append(back);authContent.append(eyebrow,h2,p,form,row);form.onsubmit=sendOtp;back.onclick=()=>renderAuth('login')}
async function passwordSignup(e){e.preventDefault();if(authBusy)return;const email=normalizeEmail($('#authEmail')?.value),password=$('#authPassword')?.value||'';if(!validEmail(email))return toast('enter a valid email address');if(!validPassword(password))return toast('use a password between 10 and 128 characters');authBusy=true;try{const{data,error}=await sb.auth.signUp({email,password});if(error||!data?.user)return toast('account creation could not be completed');if(data.session){closeAuth();await showApp(data.user);toast('account created')}else toast('check your email to verify your account')}finally{authBusy=false}}
async function passwordLogin(e){e.preventDefault();if(authBusy)return;const email=normalizeEmail($('#authEmail')?.value),password=$('#authPassword')?.value||'';if(!validEmail(email)||!password||password.length>128)return toast('invalid email or password');authBusy=true;try{const{data,error}=await sb.auth.signInWithPassword({email,password});if(error||!data?.user)return toast('invalid email or password');closeAuth();await showApp(data.user)}finally{authBusy=false}}
async function sendOtp(e){e.preventDefault();if(authBusy)return;const now=Date.now();if(now<otpCooldownUntil)return toast(`try again in ${Math.ceil((otpCooldownUntil-now)/1000)}s`);const email=normalizeEmail($('#otpEmail')?.value);if(!validEmail(email))return toast('enter a valid email address');authBusy=true;try{const{error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:`${window.location.origin}${window.location.pathname}`}});if(error)return toast('we could not send a code right now');otpCooldownUntil=Date.now()+60000;renderOtpVerify(email)}finally{authBusy=false}}
function renderOtpVerify(email){authContent.textContent='';const eyebrow=el('span',{className:'eyebrow'},'CHECK YOUR EMAIL'),h2=el('h2',{},'enter the six-digit code.'),p=el('p',{});p.textContent='we sent a one-time code to ';p.append(el('b',{},email));const form=el('form',{className:'auth-form'}),code=el('input',{id:'otpCode',inputMode:'numeric',maxLength:6,pattern:'[0-9]{6}',autocomplete:'one-time-code',placeholder:'123456',required:true}),submit=el('button',{className:'pill-btn dark',type:'submit'},'verify ↗');form.append(code,submit);const row=el('div',{className:'auth-switch'}),back=el('button',{type:'button'},'use another email');row.append(back);authContent.append(eyebrow,h2,p,form,row);form.onsubmit=async ev=>{ev.preventDefault();if(!validOtp(code.value)||authBusy)return toast('enter the six-digit code');authBusy=true;try{const{data,error}=await sb.auth.verifyOtp({email,token:code.value.trim(),type:'email'});if(error||!data?.user)return toast('invalid or expired code');closeAuth();await showApp(data.user)}finally{authBusy=false}};back.onclick=renderOtp;code.focus()}
async function logout(){const{error}=await sb.auth.signOut({scope:'global'});if(error)return toast('could not log out completely');showPublic();toast('logged out')}
function showPublic(){$('#publicView')?.classList.remove('hidden');$('#appView')?.classList.add('hidden')}
function safeText(node,value){if(node)node.textContent=value||''}
function renderSources(items,target,compact=false){target.textContent='';if(!items.length){target.append(el('div',{className:compact?'empty-row':'source-empty'},'no verified study sources have been published yet.'));return}items.forEach((s,i)=>{const row=el('div',{className:compact?'dashboard-source':'source-row'});if(!compact)row.append(el('span',{className:'source-index'},String(i+1).padStart(2,'0')));const body=el('div');body.append(el('strong',{},s.title));body.append(el('small',{},`${s.provider} · ${s.academic_year||'current source'} · ${s.source_kind.replaceAll('_',' ')}`));const a=el('a',{href:s.source_url,target:'_blank',rel:'noopener noreferrer'},'open official source ↗');row.append(body,a);target.append(row)})}
async function loadPublicSources(){const target=$('#sourceList');if(!target)return;const{data,error}=await sb.from('study_sources').select('title,provider,academic_year,source_kind,source_url').order('provider').order('title');if(error){target.textContent='verified source library unavailable right now.';return}renderSources(data||[],target,false)}
async function loadNational(){const{data,error}=await sb.from('national_tests').select('title,exam_name,scheduled_at,duration_minutes,question_count,total_marks,status').gte('scheduled_at',new Date().toISOString()).order('scheduled_at').limit(1).maybeSingle();if(error||!data){safeText($('#nationalStatus'),'not scheduled');safeText($('#nationalDetail'),'no live AUREN National test is currently published.');return}safeText($('#nationalStatus'),data.title);safeText($('#nationalDetail'),`${data.exam_name} · ${data.question_count} questions · ${data.duration_minutes} minutes`)}
async function showApp(user){if(!user?.id)return showPublic();$('#publicView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');const{data:profile}=await sb.from('profiles').select('username').eq('id',user.id).maybeSingle();const name=profile?.username||'student';safeText($('#userName'),profile?.username||'');safeText($('#welcomeName'),`welcome, ${name}.`);safeText($('#goalLine'),'your dashboard only shows data that actually exists.');const[{count:qCount},{data:sources},{data:national}]=await Promise.all([sb.from('questions').select('id',{count:'exact',head:true}),sb.from('study_sources').select('title,provider,academic_year,source_kind,source_url').order('provider').order('title'),sb.from('national_tests').select('title,exam_name,scheduled_at').gte('scheduled_at',new Date().toISOString()).order('scheduled_at').limit(1).maybeSingle()]);safeText($('#questionCount'),String(qCount??0));safeText($('#sourceCount'),String(sources?.length??0));safeText($('#dataStatus'),'live');renderSources(sources||[],$('#dashboardSources'),true);safeText($('#nextNational'),national?.title||'not scheduled');safeText($('#nextNationalNote'),national?`${national.exam_name} · ${new Date(national.scheduled_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}`:'no AUREN National test is currently published')}
$('#logoutBtn')?.addEventListener('click',logout);$('#authClose')?.addEventListener('click',closeAuth);overlay?.addEventListener('click',e=>{if(e.target===overlay)closeAuth()});$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.auth)));$('#tutorBtn')?.addEventListener('click',()=>toast('AI Tutor is being connected to your verified study data.'));
sb.auth.onAuthStateChange((_event,session)=>{if(session?.user)showApp(session.user);else showPublic()});sb.auth.getSession().then(({data:{session}})=>session?.user?showApp(session.user):showPublic());
loadPublicSources();loadNational();
const canvas=$('#ambient'),ctx=canvas?.getContext('2d');let particles=[];function resize(){if(!canvas||!ctx)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(40,Math.floor(innerWidth/34))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.3,vx:(Math.random()-.5)*.1,vy:(Math.random()-.5)*.1,a:Math.random()*.22+.05}))}function animate(){if(!canvas||!ctx)return;ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(210,106,46,${p.a})`;ctx.fill()}requestAnimationFrame(animate)}addEventListener('resize',resize);resize();animate();$('#mobileMenu')?.addEventListener('click',()=>$('.site-header nav')?.classList.toggle('mobile-open'));